# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = ClientToPlaces_client
SERVER = ClientToPlaces_server

CLIENTA = PlacesToAirport_client
SERVERA = PlacesToAirport_server

SOURCES_CLNT.c = 
SOURCES_CLNT.h = 
SOURCES_SVC.c = 
SOURCES_SVC.h = 
SOURCES.x = ClientToPlaces.x

# Airport items
SOURCESA_CLNT.c =
SOURCESA_CLNT.h =
SOURCESA_CLNT.c =
SOURCESA_SVC.h =
SOURCESA.x = PlacesToAirport.x

# places required files
TARGETS_SVC.c = ClientToPlaces_svc.c ClientToPlaces_server.c ClientToPlaces_xdr.c PlacesToAirport_xdr.c PlacesToAirport_clnt.c trie.c
TARGETS_CLNT.c = ClientToPlaces_clnt.c ClientToPlaces_client.c ClientToPlaces_xdr.c 
TARGETS = PlacesToAirport.h  ClientToPlaces.h ClientToPlaces_xdr.c ClientToPlaces_clnt.c ClientToPlaces_svc.c ClientToPlaces_client.c ClientToPlaces_server.c node.hpp kdtree.hpp

#airport required files
TARGETSA_SVC.c = PlacesToAirport_svc.c PlacesToAirport_server.c PlacesToAirport_xdr.c
TARGETSA_CLNT.c = PlacesToAirport_clnt.c PlacesToAirport_client.c PlacesToAirport_xdr.c
TARGETSA = PlacesToAirport.h PlacesToAirport_xdr.c PlacesToAirport_clnt.c PlacesToAirport_svc.c PlacesToAirport_client.c PlacesToAirport_server.c node.hpp kdtree.hpp

OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o)  $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o)

# This is the commands for airport server
OBJECTSA_CLNT = $(SOURCESA_CLNT.c:%.c=%.o)$(TARGETSA_CLNT.c:%.c=%.o)
OBJECTSA_SVC = $(SOURCESA_SVC.c:%.c=%.o)$(TARGETSA_SVC.c:%.c=%.o)

# Compiler flags 
CC = $(CXX)
CFLAGS += -g
LDLIBS += -lnsl
RPCGENFLAGS = 

# Targets 

all : $(CLIENT) $(SERVER) $(SERVERA)

#$(TARGETS) : $(SOURCES.x) 
#	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

# places stuff
$(OBJECTS_CLNT) :  $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(TARGETS_CLNT.c)


$(OBJECTS_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h) $(TARGETS_SVC.c) 

# server stuff
$(OBJECTSA_CLNT) : $(SOURCESA_CLNT.c) $(SOURCESA_CLNT.h) $(TARGETSA_CLNT.c) 

$(OBJECTSA_SVC) : $(SOURCESA_SVC.c) $(SOURCESA_SVC.h) $(TARGETSA_SVC.c) 

$(CLIENT) : $(OBJECTS_CLNT) 
	$(LINK.cc) -std=c++11 -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS) 

#Airport client
$(CLIENTA) : $(OBJECTSA_CLNT) 
	$(LINK.cc) -std=c++11 -o $(CLIENTA) $(OBJECTSA_CLNT) $(LDLIBS) 

$(SERVER) : $(OBJECTS_SVC) 
	$(LINK.cc) -std=c++11 -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

#Airport server	
$(SERVERA) : $(OBJECTSA_SVC) 
	$(LINK.cc) -std=c++11 -o $(SERVERA) $(OBJECTSA_SVC) $(LDLIBS)

trie.o : trie.c
	$(LINK.cc) -std=c++11 -c -o trie.o trie.c

ClientToPlaces_client.o : ClientToPlaces_client.c
	$(LINK.cc) -std=c++11 -c -o ClientToPlaces_client.o ClientToPlaces_client.c

ClientToPlaces_server.o : ClientToPlaces_server.c
	$(LINK.cc) -std=c++11 -c -o ClientToPlaces_server.o ClientToPlaces_server.c
	
clean:
	$(RM) ClientToPlaces_client.o ClientToPlaces_server.o ClientToPlaces_clnt.o ClientToPlaces_svc.o ClientToPlaces_xdr.o PlacesToAirport_server.o PlacesToAirport_svc.o PlacesToAirport_clnt.o trie.o PlacesToAirport_xdr.o
 
