/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "PlacesToAirport.h"

bool_t
xdr_airports (XDR *xdrs, airports *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->code, 4))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, 64))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->state, 3))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lon))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->dist))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (airports), (xdrproc_t) xdr_airports))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_LatLon (XDR *xdrs, LatLon *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lon))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_returnTypeA (XDR *xdrs, returnTypeA *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_pointer (xdrs, (char **)&objp->returnTypeA_u.resultA, sizeof (airports), (xdrproc_t) xdr_airports))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
